### ISSUE TITLE
Why are password hashes so sensitive?

### ISSUE THREAD

**Issue by aj0strow** [jeremyevans/rodauth#1]
Hey, found your project but I don't understand. 

What makes a password hash so precious to attackers? Isn't the point of using a secure crypto hash that it would take years to solve for plain text? 

If that's true, password hashes are the least valuable thing in the database, no? I'm just trying to understand. Cheers!

**Comment by jeremyevans** [comment]
Password hashes can be attacked, and attacks can be distributed.  Using a hash such as bcrypt increases the amount of effort it takes for a successful attack, but it's more secure to never allow direct access to the hash.  See if any security professional trusts their password hash enough to give you a copy of the hash.

Because of password reuse, a successful attack on a password hash can have adverse effects on external systems, making it very important to do what you can to secure them.

There may well be more important things in your database than password hashes.  For such things, a similar approach of using different database accounts for access control may be a good idea.

**Comment by aj0strow** [comment]
Thanks much appreciated. I like your database idea a lot btw, it just seemed redundant at first glance.
