### ISSUE TITLE
login_redirect_session_key set to POST request

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/rodauth#122]
I've found what it seems like a bug, when the `login_return_to_requested_location?` is enabled: Whenever I submit a form,and the subsequest POST request requires me to login, I'm redirected to login form, and when I perform to the login request, I'm redirected back to the same url I POSTed. The problem is, this URL **must** be available via GET. 

Although `rodauth` routes with a POST most of the times have a GET, this might have slipped through the cracks. But the same limitation doesn't hold in application code.

Issue seems to be: https://github.com/jeremyevans/rodauth/blob/master/lib/rodauth/features/login.rb#L89 ; `request.fullpath` is used, but no check for the verb is done.

Devise solves this [here](https://github.com/heartcombo/devise/blob/f5cc775a5feea51355036175994edbcb5e6af13c/lib/devise/failure_app.rb#L119). we can keep the `fullpath` call for `GET` requests, but get the `referer` when it's not.

Let me know what you think.

**Comment by jeremyevans** [comment]
I don't want to use referrer, but I do agree that we should skip returning to requested location for non-GET requests.

I don't consider this a major issue, because a well designed application should not expose a form that will cause such an issue, and an offsite form should either be blocked due to CSRF checking or not require login if you are allowing cross site requests.

**Comment by HoneyryderChuck** [comment]
What's the case against referer? CSRF backdoor? Won't the CSRF token already deal with that concern?

I don't think that "expect all applications to be well-designed" is a valid argument. The triggered error was not obvious and required me to investigate the source code.

I'll open a PR with the changes I've done locally later in the day (using referer, I'll wait for your input on why I should consider not using it).

**Comment by jeremyevans** [comment]
I think using the referrer blindly is likely to make CSRF attacks to forms that allow CSRF but require login much easier.  Then during an attack, if you aren't logged in, you get redirected back to the attack page instead of getting some sort of error.  There may be other security implications as well.

I'll plan on merging your pull request and then extracting the referrer use to a configuration method, so you can override it to use referrer if you want, but it isn't used by default.  Note that I've already done the release testing for 2.4.0, so this will be after the 2.4.0 release tomorrow.

**Comment by HoneyryderChuck** [comment]
> Then during an attack, if you aren't logged in, you get redirected back to the attack page ...

Could one keep the referer logic, enhanced with a "same-domain" check, i.e.  check that both `fullpath` and `referer` "refer" to the same origin? Would that comply with the security consideration?

I'm trying to find a way to make this work for POSTs, but I don't want to push it and then introduce a security bug, so if you still see some issue with the suggested proposal, feel free to drop it.

Looking better at it, [it seems that devise also ignores the redirection if original requests aren't GET](https://github.com/heartcombo/devise/blob/f5cc775a5feea51355036175994edbcb5e6af13c/lib/devise/failure_app.rb#L243).

 >  Note that I've already done the release testing for 2.4.0, so this will be after the 2.4.0 release tomorrow.

It's fine, I've worked around it already.

Thanks!
