### ISSUE TITLE
as an admin, I would like to access password hashes

### ISSUE THREAD

**Issue by catsky** [jeremyevans/rodauth#138]
hi there

We are planning a database migration and have to read the password hashes saved in this system, which using rodauth way. 
Is it possible to read password hashes of table `account_password_hashes`? and how?

thanks

**Comment by jeremyevans** [comment]
Sure, you just have to disable the security.  You should probably grant select access to the account_password_hashes table to a specific database user and use that user to extract the password hashes.

Note that since this is a question and isn't a bug report, the more appropriate forum is the Rodauth Google Group.
