### ISSUE TITLE
require_authentication doesn't check if `session[session_key]` is still existent

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/rodauth#18]
I've just noticed that, if an account has been created, and a session (I tested the JWT case, but i guess it'll happen in the raw session) has been authenticated previously, logging in will not force-check the key in the database.

Let's say that after those steps, the account is deleted. I can still issue requests with the previous session, although the account no longer exists!

The account was directly deleted in the database, not through the app. The session remained valid, and I can still query the API, which will not crash unless that session key (the account id) is used in some query to fetch more data.

**Comment by jeremyevans** [comment]
`require_authentication` not checking the database is expected, as otherwise it would be a large performance hit (extra database call per request).  Logging in should obviously not succeed if the account no longer exists (how would the username/password match in such a case?).

It's expected that if you delete a users account while they are logged in, and you are storing sessions in the cookie, the session can still issue requests.  If you want to handle that case, you either need to check the database on every request (as the single_session feature does), or just switch to storing the sessions server side instead of in the cookie (and deleting all server side sessions for the account when the account is deleted).  

Storing sessions in the cookie causes many similar issues, such as the making logout only log out the current browser session, and not all other sessions for the same account.  If this is something you want to prevent, you are probably better off switching your session store to a server side store than trying to check with the database on every request.

**Comment by TiagoCardoso1983** [comment]
The username/password wouldn't need to match as you have a valid session. Indeed you are right, this seems to be a property of the cookie-based sessions, although I fear that, even if having a server store on the server side, the behaviour would be the same until expiration, unless the session store would check everytime if the user exists, which is the same performance hit. I guess the moral of the story is, always purge sessions related to a user you delete. 

Thx for the clear-up!
