### ISSUE TITLE
When requesting password reset twice in a row user is sent invalid password reset key

### ISSUE THREAD

**Issue by 1gor** [jeremyevans/rodauth#26]
**Use case:**

A user requests a password reset but does not click on the email link sent (lost the email, got distracted etc.). After a short time he requests another password reset. He receives a another email with a new link. When he clicks on the latest received link he gets an error "invalid password reset key". 

The *first* sent email link works and takes the user to the password reset form. 

**Comment:**

I don't think this is the expected behaviour. User shoud not be sent an invalid password reset key. The expected behaviour would be for the latest password reset key sent to be always working (and previously sent keys should be invalidated).

**Illustration:**

The following spec illustrates the issue (run on master branch).

```
describe 'Rodauth reset_password feature' do
    it "should send user the latest valid reset key" do
    rodauth do
      enable :login, :reset_password
      reset_password_autologin? true
    end
    roda do |r|
      r.rodauth
      r.root{view :content=>rodauth.logged_in? ? "Logged In" : "Not Logged"}
    end
    
    # Trying to login the first time
    login(:pass=>'01234567')

    click_button 'Request Password Reset'
    link1 = email_link(/(\/reset-password\?key=.+)$/)

    # Ignoring the first email link, trying to login the second time
    login(:pass=>'01234567')

    click_button 'Request Password Reset'

    link2 = email_link(/(\/reset-password\?key=.+)$/)

   # Finding the latest password reset link and following it
    visit link2                 
    page.body.must_include("Confirm Password")     # Fails!

    # If instead
    # visit link1                 
    #  page.body.must_include("Confirm Password")     # Pass!

  end
end
```

**Comment by jeremyevans** [comment]
Thanks for the report!

The expected behavior is for the second request to be sent the same key as the first request.  Invaliding the first request key when the second request is made would lead to a trivial denial of service attack, since an attacker could just constantly request password reset keys and then if a user tried to request a password reset, the key would not be valid by the time the user tried to use it.

There is code in the password reset feature that tries to ensure the user gets the same key for future requests.  However, it appears to only handle uniqueness violations.  It needs to be modified so that it grabs a preexisting key.  verify_account suffers from the same issue in the code, though I'm not sure you can actually hit the same problem as you can't create multiple accounts with the same id.

I'll fix this today and release an new version with the fix.
