### ISSUE TITLE
Skip the views 

### ISSUE THREAD

**Issue by shafiqapandi** [jeremyevans/rodauth#263]
Is it possible to skip certain views such as validation and logout?

For Validation:
User automatically get verified when clicking on link instead of going through the form in the account_verify views

For Logout:
User automatically log out on "/logout" instead of going through the form in the logout views.

**Comment by jeremyevans** [comment]
Doing so isn't safe.  Clicking on a link uses `GET`, which is supposed to be idempotent.  Rodauth forces a user to submit a form (which uses `POST`) for all non-idempotent actions.  It is possible to configure Rodauth to do what you want by overriding `verify_account_view` and `logout_view`, but I recommend against it.

In the future, unless you are reporting a bug in Rodauth, please open a Discussion post instead of creating an issue.
