### ISSUE TITLE
Custom login/logout templates

### ISSUE THREAD

**Issue by davydovanton** [jeremyevans/rodauth#5]
Hello,
I playing with rodauth and I have a question. Can I change default templates for login and logout?
I know about [JSON API](https://github.com/jeremyevans/rodauth#json-api-support) but it's very complicated for my example.

Thanks!

**Comment by jeremyevans** [comment]
Yes.  You can use the `login_view` and `logout_view` configuration methods to override what HTML is used for the pages.  The same is true for other views.

**Comment by davydovanton** [comment]
Thanks! Can I add this to readme? I think it will be helpful not only for me.

**Comment by jeremyevans** [comment]
There's a slippery slope here.  I don't want to add a description of all possible configuration options to the README, as it is already pretty long.  The README links to the individual documentation pages for each feature, and both of these options are described on those respective pages.

**Comment by davydovanton** [comment]
I understood. Anyway, thanks for help!

**Comment by okliv** [comment]
Looks like since 2016 that slippery slop just became more slipperier just because there are a lot more features since that time. Unfortunately, i have to say that rodauth documentation is still awful in general. Just try to look to current github's readme page. There is even no any syntax highlighting... I understand, Jeremy made a great tool and this is open source and so on but if he ask himself why `rodauth` still not widely used - this is because of weak manuals (imo). I've spent more than two hours in my particular case to start use it but still have new and new errors while `rackup` my app. Links are absent in general (find `The options/methods for the supported features are listed on a separate page per feature. If these links are not active...` sentence in docs), tons of methods that are not described or described just for a mark.. For whom he is doing it? It is very sad to see that just because of luck of documentation this software is still only for people who like pain (or can read Jeremy's mind).

Hope Jeremy will read this and find something constructive in my words, it is not a hate it is just an attempt to be honest and make a push to manage documentation in more developer-friendly way. And I even would definitely help somehow with docs but my english is wished to be more good for this :(

**Comment by jeremyevans** [comment]
@okliv Is there are reason you are using the GitHub README and not the Rodauth website (http://rodauth.jeremyevans.net/rdoc/files/README_rdoc.html), which has syntax highlighting and working links?

In terms of methods not described, you are linking to an RDoc page for the Rodauth module.  RDoc doesn't handle Rodauth's features correctly, and the heavy DSL nature of features would make RDoc generated documentation for them almost worthless.  That is the reason that all configuration methods are documented separately in the appropriate feature file in the `doc` folder.  There is even a rake task to ensure that all configuration methods that you can use are documented.

The main reason Rodauth isn't popular is that it hasn't been easily usable with Rails, and most Ruby web applications that would use authentication frameworks are built with Rails.  With rodauth-rails, that may change.  I agree that more documentation would help, and I believe @janko is working on more user-friendly guides which I'll be incorporating when they are ready.

In terms of why I'm developing Rodauth, it's because I have a personal need for it and a desire to share it, since I think the approach it takes is superior to other options.  

If you would like to have a constructive conversation, it would probably be best to post in the Google Group with the errors you are receiving, so that I could try to help you debug them.

**Comment by janko** [comment]
@okliv Thank you for your feedback, I'll try to help and improve documentation. [Shrine](https://shrinerb.com/) users had fairly positive feedback about Shrine's docs, so I'll try to find time to bring some of these ideas into Rodauth documentation. I will lay some ideas soon in the google group.

Regarding syntax highlighting on GitHub, the main problem is that GitHub isn't syntax highlighting RDoc files, even though the `rdoc` tool does. I've already sent out a request to GitHub support a while ago, but they haven't addressed that yet (and recently they pushed some changes for .rdoc files where tables are now shown as definition lists, which isn't great either).

I did some digging, and I already know they're using [Linguist](https://github.com/github/linguist) for parsing, which internally uses TextMate language grammars. TextMate grammars are sort of official language syntax specifications, as all newer GUI text editors use them for syntax highlighting (Visual Studio Code, Atom, Sublime Text). Linguist seems to use [RDoc.tmbundle](https://github.com/joshaven/RDoc.tmbundle) for RDoc parsing, which [doesn't provide syntax highlighting at the moment](https://github.com/joshaven/RDoc.tmbundle#label-Notes).

In Shrine I'm using regular markdown (`.md`) which renders great on GitHub and on the website, which I'm rendering with [Docusaurus](https://docusaurus.io/) and syntax-highlighting with [atom/highlights](https://github.com/atom/highlights) library. In the early days of the project I too have started with RDoc, but I minded things like heading links being different between GitHub's and generated version (e.g. `#features` on GitHub and `#label-Features` on generated version). So I ended up with the current setup, which does require Node.js, but offers many nice features such as auto-generated TOC in a sidebar and linking related guides.

I'll first present this approach on the google group in more detail, as it's definitely more complex than the current system, so I'd like to make sure that I list all the benefits so that we can discuss the possibility of using this approach.

**Comment by jeremyevans** [comment]
I'm open to documentation changes, but not open to anything that requires external programming environments such as Node.js.  It must be possible to generate all documentation using just Ruby and gems (and preferably pure Ruby gems).

Personally, I don't see that much value in making things look better on GitHub.  The primary goal should be making the website better (most of which is currently generated via rdoc).  Mostly, I think the content should be improved (such as additional guides).  Formatting changes are of far less priority, in my opinion.

**Comment by okliv** [comment]
i am sure there is the reason why it is all as it is, and you are doing a great job. i just gave an opinion as an ordinary user, who came to github from Google at first, then to rdoc (again, somehow googling something) and only then found almost same docs but at rodauth's website. 

if there is a rifle, it has to shoot, especially if it names "most advanced" shooting tool, in my opinion.

and even rodauth website's docs are far from excellence, as there is no even a basic "quick start" really working example with all default most likely necessary features like, verification + account creation + ... (not only `:login, :logout`). as a ruby/rails dev, i probably used a devise/clearance, and now looking for something more usable, **simple**(in terms of implementation) and "featureable". but i have to dig every single peace of settings just to start using it (i didn't find any docs how to implement **fully working** passwordless `email_auth`, for example.. even `enable :email_auth` i only found while I read all docs from A to, thanks to Lord, E and then blindly tried it as a row in a rodauth configuration block ... but how `email_auth` (`_auth` - semantically, fully-featured word) has to work during sign up procedure (especially email verification still **without** password) - i still didn't get for now.

thanks for inviting to google groups, but this is an another awful, ancient, from 20th century something for devosaurs that impossible to use for constructive, result oriented, dev related modern conversations (imo, of course).

**Comment by jeremyevans** [comment]
As I stated earlier, I agree that more introductory guides would be beneficial.  Other than the README, most of Rodauth's documentation would be considered reference documentation as opposed to guides.  However, due to the number of Rodauth features, it's basically impossible to have a guide for every possible use case.

In terms of your specific example of passwordless email auth with email verification, I'm guessing something like this:

```ruby
plugin :rodauth do
  enable :login, :login, :email_auth, :verify_account
  create_account_set_password? false
  verify_account_set_password? false
end
```

I guess the information for how that is setup is on 3 separate pages (README, create_account documentation, verify_account documentation). I expect that the average developer using Rodauth would be able to use the documentation to come to that result, but perhaps I am being unrealistic.

In regards to Google Groups, I guess it isn't for everyone, but what it does it does fine.  My personal feeling is the content is far more important than the medium used, but not everyone apparently shares that outlook.  I can say that there are plenty of other developers who have used it for constructive, result oriented, dev related modern conversations, so it's definitely not impossible for everyone to use, even if it is impossible for you. Also, just FYI, Google Groups didn't come out until the 21st century. :)

**Comment by janko** [comment]
> if there is a rifle, it has to shoot, in my opinion. if there are three rifles they have to shoot all.

RDocs are used mainly for feature docs and README, I agree that if you just open the RDoc index page, you have to figure out where to look, it's better to follow links on the documentation page directly.

One improvement I would see here is *not* linking to the Rdoc index page, because it seems to me that all important documentation pages are accessible through other links on that page.

> and even rodauth website's docs are far from excellence, as there is no even a basic "quick start" really working example with all default most likely necessary features

Are you using Rails? The rodauth-rails' generator creates a Rodauth app with some common features enabled, with examples of various configuration options in the comments. Coupled with Rodauth's built-in templates it's more than enough to get started.

> i didn't find any docs how to implement fully working passwordless email_auth

Yes, I agree the behaviour of `email_auth` isn't explained in enough detail in the documentation. I'm still planning to finish a common set of how-to guides and make a PR, with Jeremy's example above included, and I would also like to expand the feature documentation as well.

Truth be told, I quickly found it easier to just switch to reading the source code to find out about various configuration options, because the code was so well-refactored. I would sometimes read the method description in the docs, but usually I would gain a better understanding through the code. I know this probably isn't possible for most, but it's something that would be much much harder to do with gems like Devise, because of their complexity.

> thanks for inviting to google groups, but this is an another awful, ancient, from 20th century

Rails core used google groups a few months ago before switching to Discourse. If it worked for Rails core, than it's probably good enough. I've used google groups for Shrine before switching to Discourse several months ago as well, and it was fairly active.

My reasons for switching was that I wanted an app-like experience, with bigger letters, markdown fenced blocks for syntax highlighting etc. The tipping point was when google groups would sometimes swallow new threads, without it appearing in the moderation section, so I had nothing to approve.

Discourse was an obvious improvement in every way, I would love to help set up something like that for Rodauth as well if Jeremy is open to that. The only thing I haven't yet set up is the ability for people to reply via email, I will probably figure out how to do that eventually (Rails' Discourse has that set up AFAIK). Though it's ironic that Rodauth google group doesn't allow me to reply via email either at the moment:

<img width="730" alt="Screenshot 2020-05-29 at 10 29 29" src="https://user-images.githubusercontent.com/795488/83238833-4a7c1180-a197-11ea-8917-2369a51d577e.png">

I also couldn't find some finished scripts for moving existing google group posts over to Discourse, I'm wondering how Rails did it.
